services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat_network

  cassandra:
    image: cassandra:5.0
    ports: 
      - 7000:7000
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cassandra-status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat_network

  migrate:
    image: migrate/migrate
    profiles: ["tools"]
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable",
        "up",
      ]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  cassandra_data:
  
networks:
  chat_network:
    driver: bridge