// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (*TblUser, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetUserByEmail(ctx context.Context, email string) (*TblUser, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (*TblUser, error)
	ListUsers(ctx context.Context) ([]*TblUser, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*TblUser, error)
}

var _ Querier = (*Queries)(nil)
